### PR TITLE
status minor fixes

### LINKED ISSUE #1230: Status Tab - UI Clean Up
- Status history not showing correctly when 1 status has been approved
- Read More / Read Less behaviour is weird
- Dont expand status preview box to be same height as status history box
- Show More doesnt need to be there if there arent more statuses to show

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

### PR DESCRIPTION
**Pull request by TomChapmanGov**
#1230

### CODE REVIEW

**Review by jadmnsaad — APPROVED** [review]

File: epictrack-web/src/components/workPlan/status/StatusView/StatusHistory/HistoryItem.tsx [hunk 1]
```diff
@@ -68,7 +69,7 @@ const HistoryItem = ({ status }: HistoryItemProps) => {
           <TimelineContent>
             <Box>
               <ETStatusHistoryDate>
-                {moment(status.posted_date).format("L")}
+                {moment(status.posted_date).format("MMM.DD YYYY")}
```
Comment (dinesh-aot) [inline epictrack-web/src/components/workPlan/status/StatusView/StatusHistory/HistoryItem.tsx]: I think we will use this format in many other places. Shall we have this as a constant. We already have DATE_FORMAT as a constant. This can be another format.

File: epictrack-web/src/components/workPlan/status/StatusView/StatusHistory/HistoryItem.tsx [hunk 2]
```diff
@@ -83,50 +84,26 @@ const HistoryItem = ({ status }: HistoryItemProps) => {
...
-                      Edit
-                    </Button>
-                  </Then>
-                </If>
-              </>
-            ) : (
-              <Box>
-                {status.description.slice(0, 50)}...
+            <ReadMoreText>{status?.description}</ReadMoreText>
+            <If condition={hasPermission() && statusHighlight === status.id}>
```
Comment (dinesh-aot) [inline epictrack-web/src/components/workPlan/status/StatusView/StatusHistory/HistoryItem.tsx]: Since there is no "Else", this can be "When"

**Review by dinesh-aot — APPROVED** [review]
