### PR TITLE
Filter in insights->staff list fix

### LINKED ISSUE #1874: All Filters Expected Ordering
---
**CARLY/CONNOR: please add more info to this card - like a table checklist of all pages with Filters/Tables/Filter Headers**

update TableFilter to have natural sort by default

the only exception should be Staff page in List management. (and only because the position filter has already been sorted hieratically)

---

**As a** user

**I want** Natural sorting to be the default on filters

**so that** I know where I can expect to find options in the dropdown

### Scenario 1: 

GIVEN I am interacting with any grid
WHEN I open a filter
THEN I see the options are sorted by natural sort

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

### PR DESCRIPTION
**Pull request by dinesh-aot**
#1874

### CODE REVIEW

**Review by djnunez-aot — APPROVED** [review]

File: epictrack-web/src/components/insights/Work/Tabs/Staff/Charts/workListing.tsx [hunk 1]
```diff
@@ -57,7 +57,10 @@ const WorkList = () => {
     return (
       workStaffs
         ?.map((workStaff) => workStaff.work_lead.full_name)
-        .filter((lead) => lead)
+        .filter(
+          (lead, index, arr) =>
+            lead && arr && arr.findIndex((t) => t === lead) === index
```
Comment (jadmnsaad) [inline epictrack-web/src/components/insights/Work/Tabs/Staff/Charts/workListing.tsx]: What is arr.findIndex((t) => t === lead) === index doing?
